### ISSUE TITLE
I got some questions!

### ISSUE THREAD

**Issue by b-e-y** [ardha27/AI-Waifu-Vtuber#2]
can the ai speak in english?
also can i use this with google translate instead of deepL?
like a good addition would be using google translate if someone doesn't want to use DeepL
and lastly can we use this with twitch?
and if you can add a demo, because the current demo doesn't work. at least a short video showcasing the ai!
after good work and hope for the best for you!

**Comment by ardha27** [comment]
1. i use voicevox to synthesize the audio, and voicevox only accept input and output in Japanese. If you want to make it speak in english, maybe you can find another alternative
2. yes you can use google translate instead of deepl. I use deepl because it can produce more casual translation from EN to JP
3. i 've never tried it, but i think you can use it to capture twitch livestream chat if you use twitch API or twitch python library?
4. i already fix the broken demo link, you can check it now

**Comment by b-e-y** [comment]
oh thanks for answering that's really cool to see, how you made this 👍🏻
